// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'ap-southeast-2:728f9655-78ac-4a7d-86ee-f5dc505420b5',
    'aws_cognito_region': 'ap-southeast-2',
    'aws_content_delivery': 'enable',
    'aws_content_delivery_bucket': 'authexample-hosting-mobilehub-10262280',
    'aws_content_delivery_bucket_region': 'ap-southeast-2',
    'aws_content_delivery_cloudfront': 'enable',
    'aws_content_delivery_cloudfront_domain': 'd1hhti5ni0mnri.cloudfront.net',
    'aws_mandatory_sign_in': 'enable',
    'aws_mobile_analytics_app_id': 'c85267fd893c4a7ca29848ef81b75f84',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': '8b3e318f-1453-11e8-b7ec-1579a7b87ac8',
    'aws_project_name': 'auth-example-2018-02-18-13-29-18',
    'aws_project_region': 'ap-southeast-2',
    'aws_resource_name_prefix': 'authexample-mobilehub-10262280',
    'aws_sign_in_enabled': 'enable',
    'aws_user_pools': 'enable',
    'aws_user_pools_id': 'ap-southeast-2_Y9InDpx7k',
    'aws_user_pools_mfa_type': 'OFF',
    'aws_user_pools_web_client_id': '5s21a1h9gklvdh9587t0v3srbm',
}

export default awsmobile;
